service:
  transaction:
    timeout: ${JPA_TX_TIMEOUT:3} # seconds

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}

spring:
  devtools:
    livereload:
      enabled: false
    add-properties: false